### ISSUE TITLE
Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by soichih** [joyent/node-sshpk-agent#11]
If ssh-agent is not running properly, sshpk-agent generates following error message.

```
Sat Jun 24 2017 13:30:06 GMT+0000 (UTC) - error: Sat, 24 Jun 2017 13:30:06 GMT uncaughtException: Uncaught, unspecified "error" event. (undefined)
 Sat Jun 24 2017 13:30:06 GMT+0000 (UTC) - error: Error: Uncaught, unspecified "error" event. (undefined)
     at Client.emit (events.js:163:17)
     at Immediate.<anonymous> (/app/node_modules/sshpk-agent/lib/client-fsm.js:313:9)
     at runCallback (timers.js:649:20)
     at tryOnImmediate (timers.js:622:5)
     at processImmediate [as _immediateCallback] (timers.js:594:5)
```

It should generate a better error message - something that indicates that ssh-agent is broken.

**Comment by arekinath** [comment]
https://cr.joyent.us/#/c/2368
